[package]
name = "libressl-src"
version = "111.10.0+3.1.2"
authors = ["Dubiousjim <dubiousjim@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Source of LibreSSL and logic to build it."
repository = "https://github.com/dubiousjim/libressl-src"
readme = "README.md"
exclude = ['libressl/*']

[workspace]
members = ['testcrate']

[dependencies]
# autotools = "0.2.1"
# autotools = { git = "https://github.com/lu-zero/autotools-rs" }
autotools = { git = "https://github.com/dubiousjim/autotools-rs" }
